[package]
name = "tauri-react-zerotier-toolkit"
version = "0.0.1"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
tauri = { version = "1.5", features = [ "http-request",
    "process-exit",
    "shell-open",
    "process-command-api",
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
env_logger = "0.11.0"
lazy_static = { version = "1.4.0", features = [] }
chrono = "0.4.31"
winapi = { version = "0.3.9", features = ["winsvc", "winbase"] }
parking_lot = "0.12.1"
[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
